apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend-deployment
  namespace: workshop
  labels: 
    role: api
    env: demo
spec: 
  replicas: 2
  selector: 
    matchLabels:
      role: backend
  template:
    metadata:
      labels:
        role: backend
    spec:
      containers:
      - name: backend
        image: 637423640624.dkr.ecr.ap-southeast-1.amazonaws.com/three-tier-backend:latest
        imagePullPolicy: Always
        env:
          - name: MONGO_CONN_STR
            value: “mongodb://mongodb-service:27017/todo”
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secrets
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secrets
                key: password
        ports:
        - containerPort: 3500
        livenessProbe: 
          httpGet:
            path: /ok
            port: 3500
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ok
            port: 3500
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
