apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: workshop
spec: 
  selector:
    app: backend 
  ports:
  - port: 3500
    targetPort: 3500
    protocol: TCP
  type: ClusterIP

